name: 'publish'

on:
  push:
    branches:
      - master

jobs:
  resease:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.1.1
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          registry-url: 'https://npm.pkg.github.com'
          scope: '@owner'
      - name: publish
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
